### ISSUE TITLE
loading models to CPU

### ISSUE THREAD

**Issue by rhoposit** [RF5/simple-autovc#4]
Hello, I am having some issues loading the pre-trained models from torch.hub.load for the autovc and hifigan. No matter what I try, it gives me an error about CUDA. I have tried using map_location='cpu' but it does not seem to recognise this option in torch.hub.load. Do you have any suggestions?

**Comment by RF5** [comment]
Hi, yes unfortunately the way I've saved the hifhigan checkpoint and the way I have implemented the `hubconf.py` means that it assumes you have a gpu. There are a few possible solutions: 
- Use google colab to load the model (since it has a free gpu)
- Modify the `hubconf.py` code to map the checkpoint location to cpu (you might also have to tweak some internal model code  if there are any `.cuda()`'s anywhere) -- if you do this feel free to make a PR into this repo, I'm sure others might find a cpu-only variant useful. 
- Load it on a machine which has a gpu, then move the models to the cpu, and save the new state dicts/config to a cpu checkpoint, then load from that in the future. 

Sorry the current version doesn't work on cpu-only machines, but hopefully the above helps a bit!

**Comment by rhoposit** [comment]
Thanks for this! I managed to get a .pt model downloaded, but I'm still having some troubles. 

When I run the following, I get this error. Does the file `data.pkl` mean anything to you? I'm not sure what it is.. 

`model = torch.load("simple-autovc-hifigan.pt")`
```Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    model = torch.load("simple-autovc-hifigan.pt")
  File "/Users/admin/miniconda3/envs/audio/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/admin/miniconda3/envs/audio/lib/python3.8/site-packages/torch/serialization.py", line 1045, in _load
    data_file = io.BytesIO(zip_file.get_record(pickle_file))
RuntimeError: PytorchStreamReader failed locating file data.pkl: file not found
```

**Comment by RF5** [comment]
It looks like you are having trouble loading the vocoder -- I think the `.pt` file you downloaded is only the AutoVC model checkpoint, and not the vocoder checkpoint? I'm not too sure why it can't find the data.pkl in your .pt model. 

What does the model  checkpoint you made look like? Does it contain both the hifigan and autovc checkpoint?

**Comment by rhoposit** [comment]
These are the files that downloaded, and they were saved to my .cache in torch hub. I don't know the architecture of the models as I have not successfully loaded them back up after this initial download. 

```
 ls -l /Users/admin/.cache/torch/hub
total 109856
drwxr-xr-x  15 admin  staff       480  6 Jul 13:41 RF5_simple-autovc_master
drwxr-xr-x   4 admin  staff       128 23 Oct  2021 checkpoints
-rw-------   1 admin  staff  55794741  6 Jul 13:10 simple-autovc-hifigan.pt
```

And in the checkpoints folder, I have:
```
ls -l /Users/admin/.cache/torch/hub/checkpoints/
total 264224
-rw-------  1 admin  staff  112600254 23 Oct  2021 tacotron2_english_characters_1500_epochs_wavernn_ljspeech.pth
-rw-------  1 admin  staff   17475004 23 Oct  2021 wavernn_10k_epochs_8bits_ljspeech.pth
```

**Comment by RF5** [comment]
Hi @rhoposit , yeah without debugging on your local machine I don't think it will be too easy for me to figure out what is going on with that checkpoint. 

So, instead, I updated the repo to now work for cpu-only inference. Please try the standard get-started guide on the readme again and it should work on a cpu-only machine. Also note that librosa had a backwards incompatible change so I've specified on the updated readme that librosa must be at most v0.9.2. 

Hopefully it works out-of-the-box now :)

**Comment by rhoposit** [comment]
Many thanks! This works for me.

**Comment by rhoposit** [comment]
Hi @RF5 I have another similar request - we are having the same difficulty getting the convgru_embedder speaker embeddings model to load to CPU. I had a look at the ge2e_embedding.py file, and it seems that it is defaulting to CUDA on line 98. Is it possible you could make a similar change on this file, as you did before? (i.e. if cuda is not available, use CPU or just map to cpu as default)?

https://github.com/RF5/simple-speaker-embedding/blob/master/ge2e_embedding.py

**Comment by RF5** [comment]
Hi @rhoposit , I tested and the current code already works with both cpu and gpu only systems. You must simply specify the correct device when loading it from torchhub, i.e. when loading simply go:

```python
 import torch
 model = torch.hub.load('RF5/simple-speaker-embedding', 'convgru_embedder', device='cpu')
 model.eval()
```

And that should work :)
